{% set name = "zmesh" %}
{% set version = "1.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 63c0d9c90da40a29b9693d3930ffeb1092aeddb92c600cdbd2acf918b736b72f

build:
  skip: true  # [win]
  number: 2
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - cython <3
    - pbr
    - numpy
  run:
    - python

test:
  imports:
    - zmesh

about:
  home: https://github.com/seung-lab/zmesh
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: Multi-Label Marching Cubes & Mesh Simplification

  dev_url: https://github.com/seung-lab/zmesh

extra:
  recipe-maintainers:
    - mdraw
