{% set version = "1.11.1" %}

package:
  name: zmesh
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/z/zmesh/zmesh-{{ version }}.tar.gz
  sha256: 32c08878eaf1703f54ab707a0027f571a380a63e8804e7a7746ee4dd077e5ea1

build:
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - pbr                               # [build_platform != target_platform]
  host:
    - python
    - setuptools
    - wheel
    - numpy
    - cython
    - pbr
    - pip
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - zmesh
  commands:
    - pip check
  requires:
    - pip
    - python

about:
  home: https://github.com/seung-lab/zmesh/
  summary: Multilabel marching cubes and simplification of volumetric data.
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - KRiedmiller
    - mdraw
