{% set name = "zmesh" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ff168f1c2acea1b532db2ed6b6b448e91975adc6125f382b7d9694cd427e85cc

build:
  skip: true  # [win]
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - pbr
    - numpy
    - boost
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - zmesh

about:
  home: https://github.com/seung-lab/zmesh
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: Multi-Label Marching Cubes & Mesh Simplification

  dev_url: https://github.com/seung-lab/zmesh

extra:
  recipe-maintainers:
    - mdraw
