{% set version = "1.11.0" %}

package:
  name: zmesh
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/z/zmesh/zmesh-{{ version }}.tar.gz
  sha256: 97311aed518cb8524291740ffb8c445ed022abcdf58f260366bd32d8f93348c4

build:
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - wheel
    - numpy
    - cython
    - pbr
    - pip
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - zmesh
  commands:
    - pip check
  requires:
    - pip
    - python

about:
  home: https://github.com/seung-lab/zmesh/
  summary: Multilabel marching cubes and simplification of volumetric data.
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - KRiedmiller
    - mdraw
