{% set name = "zmesh" %}
{% set version = "1.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f42117207157a6193d6bf708e47b7a943decfce3baf156f53d802320b99b547f

build:
  skip: true  # [win]
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - pbr
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - zmesh

about:
  home: https://github.com/seung-lab/zmesh
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: Multi-Label Marching Cubes & Mesh Simplification

  dev_url: https://github.com/seung-lab/zmesh

extra:
  recipe-maintainers:
    - mdraw
