{% set name = "zmesh" %}
{% set version = "0.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 36ffac2d0753fede681742e5a718b2b45fd3fa951a0dcf69cca454bcba861e30

build:
  skip: true  # [win]
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - pbr
    - numpy
    - boost
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - zmesh

about:
  home: https://github.com/seung-lab/zmesh
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: Multi-Label Marching Cubes & Mesh Simplification

  dev_url: https://github.com/seung-lab/zmesh

extra:
  recipe-maintainers:
    - mdraw
