travis:
  secure:
    BINSTAR_TOKEN: uwXfkMWzW3WGQI0jooitThiFXfT1CkdFHdhrNIaBFoyUxfdJolrwilzTGXbwsYCs6llZ8n6pJjaY0AW+AyozoJryzS9ARC4bEeJ0WJuk2UfrdF9C1ebsg4D7R/xFI8QzXKTM35aqLb55ghYj+QiTWxvM4daG7vPgbTqafpuY41gNSgBjg/9nQyksRX/7oItThO1elStc1xPMj69WTdjCbHDydkXp16aJgCUpfsO2i+iz/1GCtzVbQDQmWt/kcX51FX4HSYp7jMZLaDNOPiEWGxa9Ud0pKbYeQ430ja4BlQF3ZdppJm3o7PHpVpueCg+cpLeom7ho9Tt+7uQFrqa+c+hyN0CENvFs+IcnZsHM0iYjHfsHapcthW+iDjan1X3RQcFu8pBWH6RaOXVDNI0JIYodMyV3G7VvWh/ZdJIpfAKv5RT2eXsZQKQ0BtjOR7UyRcFoj/cYlxWT2zQGIT4dwwuVM/jIjzA7kDO1kQlxPL5Ece9mWh85O9jdZD4k3I/z3JbR5tkHTDkj5F+qdqOM38BAYcGlwen9lUL44TXzEesWdZDCfceXKWe+dL+9BktWL/s4VONolQ7DcrT6CfGJztx9YSg3Y1jFvrtm4jxERWyeo+j7zQ2Pddu8wP1wTpgYAlQhzhWlGDsU0XnWdx1wgxb8/oAFkNzs6dlbRRkO5qM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
